# Generated by Django 5.2.5 on 2025-08-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_module', '0003_remove_arduinodevice_owner'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArduinoSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='00:00')),
                ('end_time', models.TimeField(default='23:59')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arduino_schedule', to='arduino_module.arduinodevice')),
            ],
        ),
    ]
