# Generated by Django 5.2.5 on 2025-08-22 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arduinodevice',
            name='active',
        ),
        migrations.RemoveField(
            model_name='arduinodevice',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='arduinodevice',
            name='name',
        ),
        migrations.AlterField(
            model_name='arduinodevice',
            name='login',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='arduinodevice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
