# Generated by Django 5.2.5 on 2025-08-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_module', '0002_remove_arduinodevice_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arduinodevice',
            name='owner',
        ),
    ]
